version: '3.4'

services:
  snippetboxdb:
    image: postgres
    container_name: snippetboxdb
    restart: always
    environment:
      POSTGRES_DB: snippetbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dxrk
      PGDATA: /pg/data
      CONFIGS: "listen_addresses:'*'"
    volumes: 
      - postgres:/pg/data
    ports:
      - "5432:5432"

  snippetboxapi:
    image: ${DOCKER_REGISTRY-}snippetbox
    container_name: snippetbox
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    depends_on: 
      - snippetboxdb

networks:
  postgres:
    driver: bridge

volumes:
    postgres: